name: VSFPRO1
favicon: null
layout_spectrum: 0.9641936207190156
typography_spectrum: 0.4228190139401704
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#212930'
    - '#6e6e6e'
    - '#6dde00'
    - '#e10315'
  brandStrength: 0.25
  lightness: 0.21355829993262887
  saturation: 0.37274777540005744
  rhythmicContrast: 0.5915954785887152
purpose: []
