name: VSFPRO1
favicon: null
layout_spectrum: 0.7503
typography_spectrum: 0.54805
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#212930'
    - '#6e6e6e'
    - '#6dde00'
    - '#e10315'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
